/* Matchday – ohne Abhängigkeiten. Teamlisten: teams.txt */
document.addEventListener('DOMContentLoaded', () => {
  'use strict';
  const $ = (s, el = document) => el.querySelector(s);
  const esc = (v='') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const uid = () => Math.random().toString(36).slice(2, 10);
  const shuffle = a => { const b=[...a]; for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];} return b; };
  const power2 = n => n > 1 && !(n & (n - 1));
  const cookieKey='matchday_state';
  const defaults = () => ({kind:null, systems:[], fields:1, format:'table', legs:1, groups:2, qualifiers:2, thirdPlace:false, teamMode:'random', category:'International', customTeams:'', players:[], matches:[], groupsData:[], bracket:[], swissRounds:0, activeTab:'matches', created:false});
  let state = load() || defaults(); let teamLists = fallbackTeams(); let focusRestore = null;

  function save(){
    const value=encodeURIComponent(JSON.stringify(state)); const chunks=value.match(/.{1,3500}/g)||[''];
    document.cookie.split(';').map(x=>x.trim()).filter(x=>x.startsWith(cookieKey+'_')).forEach(x=>document.cookie=x.split('=')[0]+'=;max-age=0;path=/;SameSite=Lax');
    chunks.forEach((v,i)=>document.cookie=`${cookieKey}_${i}=${v};max-age=31536000;path=/;SameSite=Lax`);
    document.cookie=`${cookieKey}_count=${chunks.length};max-age=31536000;path=/;SameSite=Lax`;
    try{localStorage.setItem(cookieKey,JSON.stringify(state));}catch(e){}
  }
  function load(){try{const all=Object.fromEntries(document.cookie.split('; ').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),x.slice(i+1)]}));const n=+all[cookieKey+'_count'];if(n){return JSON.parse(decodeURIComponent(Array.from({length:n},(_,i)=>all[cookieKey+'_'+i]||'').join('')))}return JSON.parse(localStorage.getItem(cookieKey)||'null')}catch(e){return null}}
  function fallbackTeams(){return {'1. Bundesliga':['FC Bayern München','Bayer 04 Leverkusen','Borussia Dortmund','RB Leipzig','VfB Stuttgart','Eintracht Frankfurt','SC Freiburg','TSG Hoffenheim','1. FSV Mainz 05','Werder Bremen','VfL Wolfsburg','FC Augsburg','Borussia Mönchengladbach','1. FC Union Berlin','FC St. Pauli','Holstein Kiel','VfL Bochum','1. FC Heidenheim'],International:['Real Madrid','FC Barcelona','Manchester City','FC Liverpool','Arsenal','Paris Saint-Germain','Inter Mailand','AC Mailand','Juventus','Atlético Madrid','FC Bayern München','Borussia Dortmund','SSC Napoli','Chelsea','Manchester United','Tottenham Hotspur'],Nationalmannschaften:['Argentinien','Frankreich','Spanien','England','Brasilien','Portugal','Niederlande','Belgien','Deutschland','Italien','Uruguay','Kolumbien','Kroatien','Marokko','Japan','USA']};}
  fetch('teams.txt').then(r=>r.ok?r.text():Promise.reject()).then(parseTeams).catch(()=>render());
  function parseTeams(text){let cat='',out={};text.split(/\r?\n/).forEach(line=>{line=line.trim();const m=line.match(/^\[(.+)]$/);if(m){cat=m[1];out[cat]=[];}else if(cat&&line&&!line.startsWith('#'))out[cat].push(line);});if(Object.keys(out).length)teamLists=out;render();}
  function currentTeams(){ if(state.category==='Individuell')return state.customTeams.split(/\n|,/).map(x=>x.trim()).filter(Boolean); return teamLists[state.category]||[]; }
  function captureScroll(){return [...document.querySelectorAll('[data-scroll-key]')].map(e=>[e.dataset.scrollKey,e.scrollTop,e.scrollLeft]);}
  function restoreScroll(list){requestAnimationFrame(()=>list.forEach(([k,t,l])=>{const e=document.querySelector(`[data-scroll-key="${k}"]`);if(e){e.scrollTop=t;e.scrollLeft=l;}}));}
  /* Auch noch nicht bestätigte Texteingaben bleiben bei jedem Neuzeichnen erhalten. */
  function syncPlayerDrafts(){document.querySelectorAll('[data-player-name]').forEach(el=>{const p=getPlayer(el.dataset.playerName);if(p)p.name=el.value;});document.querySelectorAll('[data-player-team]').forEach(el=>{const p=getPlayer(el.dataset.playerTeam);if(p)p.team=el.value;});}
  function render(){syncPlayerDrafts();const memory=captureScroll();renderSetup();renderPlayers();renderTournament();save();restoreScroll(memory);if(focusRestore){const f=focusRestore;focusRestore=null;requestAnimationFrame(()=>document.querySelector(`[data-match="${f.match}"] [data-score="${f.score}"]`)?.focus());}}
  function renderSetup(){
    const panel=$('#setup'); const showDetails=!!state.kind;
    panel.innerHTML=`<h1>Dein Fußballturnier</h1><p class="subtitle">Erstelle Spielplan, Tabelle und K.-o.-Phase an einem Ort.</p>
      <div class="setup-step ${showDetails?'setup-locked':''}"><h2>1. Turnierart</h2><div class="choice-grid">
      ${choice('kind','fifa','🎮','FIFA-Turnier','Konsolen, Teams und ausgeglichene Zuordnung')}${choice('kind','normal','⚽','Normales Turnier','Felder und klassischer Spielbetrieb')}</div></div>
      ${!showDetails?'':setupDetails()}`;
  }
  function choice(name,val,ico,title,small){return `<label class="choice ${state[name]===val?'selected':''}"><input type="radio" name="${name}" value="${val}" ${state[name]===val?'checked':''}><span>${ico}</span><strong>${title}</strong><small>${small}</small></label>`}
  function setupDetails(){const fifa=state.kind==='fifa';const cats=[...Object.keys(teamLists),'Individuell'];return `<div class="setup-step"><h2>2. Einstellungen</h2><div class="form-grid">
    <label>Turniermodus<select data-setting="format"><option value="table" ${state.format==='table'?'selected':''}>Nur Tabelle</option><option value="ko" ${state.format==='ko'?'selected':''}>Nur K.-o.</option><option value="groupsko" ${state.format==='groupsko'?'selected':''}>Gruppen + K.-o.</option><option value="swiss" ${state.format==='swiss'?'selected':''}>Schweizer System</option></select></label>
    <label>Spielrunden<select data-setting="legs"><option value="1" ${state.legs===1?'selected':''}>Einfachrunde</option><option value="2" ${state.legs===2?'selected':''}>Hin- / Rückrunde</option></select></label>
    ${fifa?`<label>Team-Modus<select data-setting="teamMode"><option value="random" ${state.teamMode==='random'?'selected':''}>Zufällig</option><option value="choose" ${state.teamMode==='choose'?'selected':''}>Auswahl</option></select></label><label>Team-Kategorie<select data-setting="category">${cats.map(x=>`<option ${state.category===x?'selected':''}>${x}</option>`).join('')}</select></label>${state.category==='Individuell'?'<label>Eigene Teams (Komma oder Zeile)<input data-setting="customTeams" value="'+esc(state.customTeams)+'" placeholder="Team A, Team B …"></label>':''}`:`<label>Anzahl der Felder<input data-setting="fields" type="number" min="1" max="20" value="${state.fields}"></label>`}
    ${['groupsko'].includes(state.format)?`<label>Gruppen<input data-setting="groups" type="number" min="2" max="8" value="${state.groups}"></label><label>Weiter pro Gruppe<select data-setting="qualifiers"><option value="1" ${state.qualifiers===1?'selected':''}>1</option><option value="2" ${state.qualifiers===2?'selected':''}>2</option><option value="3" ${state.qualifiers===3?'selected':''}>3</option><option value="4" ${state.qualifiers===4?'selected':''}>4</option></select></label>`:''}
    ${fifa?`<div><label>Konsolen-Systeme</label><div class="systems">${state.systems.map(s=>`<div class="system-row"><select aria-label="System" data-system-type="${s.id}"><option value="PS5" ${s.type==='PS5'?'selected':''}>PS5</option><option value="XBOX" ${s.type==='XBOX'?'selected':''}>Xbox</option></select><input aria-label="Anzahl ${s.type}" data-system-count="${s.id}" type="number" min="1" max="12" value="${s.count}"><button class="danger small" data-action="delete-system" data-id="${s.id}" ${state.systems.length===1?'disabled':''}>×</button></div>`).join('')}</div><button class="secondary small" data-action="add-system">+ System</button></div>`:''}
    </div>${state.format==='ko'?'<label class="toggle"><input type="checkbox" data-setting="thirdPlace" '+(state.thirdPlace?'checked':'')+'> Spiel um Platz 3</label>':''}
    <div class="actions"><button data-action="continue">Weiter zur Spielerliste →</button>${state.created?'<button class="danger" data-action="reset">Turnier zurücksetzen</button>':''}</div></div>`;}
  function renderPlayers(){const p=$('#playersPanel');if(!state.kind){p.classList.add('hidden');return;}p.classList.remove('hidden');const teams=currentTeams();p.innerHTML=`<div class="players-head"><div><h2>Spieler</h2><p class="hint">Namen direkt bearbeiten. ${state.kind==='fifa'?'Teams werden '+(state.teamMode==='choose'?'ausgewählt':'zufällig vergeben')+'.':''}</p></div><div class="actions"><button class="secondary" data-action="random-groups" ${state.format!=='groupsko'||state.players.length<2?'disabled':''}>⤨ Gruppen zufällig zuordnen</button><button data-action="add-player">+ Spieler</button></div></div><div class="players-list">${state.players.map((p,i)=>`<div class="player-card"><span class="player-num">${i+1}</span><input aria-label="Spieler ${i+1}" data-player-name="${p.id}" value="${esc(p.name)}" placeholder="Spielername">${state.kind==='fifa'?teamInput(p,teams):''}<button class="danger small" aria-label="${esc(p.name)} löschen" data-action="delete-player" data-id="${p.id}">×</button></div>`).join('')||'<div class="empty"><span>👥</span><p>Füge mindestens zwei Spieler hinzu.</p></div>'}</div><div class="footer-actions"><button data-action="generate" ${state.players.length<2?'disabled':''}>Spielplan erstellen</button></div>`;}
  function teamInput(p,teams){if(state.category==='Individuell')return `<input data-player-team="${p.id}" value="${esc(p.team||'')}" placeholder="Team">`;const opts=teams.map(t=>`<option ${p.team===t?'selected':''}>${esc(t)}</option>`).join('');return state.teamMode==='choose'?`<select aria-label="Team für ${esc(p.name)}" data-player-team="${p.id}"><option value="">Team wählen …</option>${opts}</select>`:`<span class="pill">${esc(p.team||'wird gelost')}</span>`;}
  function renderTournament(){const box=$('#tournamentPanel');if(!state.created){box.classList.add('hidden');return;}box.classList.remove('hidden');const tabs=state.format==='groupsko'?['groups','ko']:state.format==='ko'?['ko']:state.format==='swiss'?['matches','table']:['matches','table'];let content=state.activeTab==='table'?renderTable(state.players,state.matches,'Gesamttabelle'):state.activeTab==='groups'?renderGroups():state.activeTab==='ko'?renderBracket():renderMatches(state.matches,'Spiele');box.innerHTML=`<div class="panel toolbar"><h2>${esc(titleForFormat())}</h2><div class="tabs">${tabs.map(t=>`<button class="tab ${state.activeTab===t?'active':''}" data-action="tab" data-tab="${t}">${({matches:'Spiele',table:'Tabelle',groups:'Gruppen',ko:'K.-o.-Baum'})[t]}</button>`).join('')}</div><button class="ghost small" data-action="reset">Neu starten</button></div><div class="view">${content}</div>`;}
  function titleForFormat(){return ({table:'Ligaturnier',ko:'K.-o.-Turnier',groupsko:'Gruppenphase & K.-o.',swiss:'Schweizer System'})[state.format];}
  function renderMatches(matches,title){return `<div class="section-card"><h2>${title}</h2><div class="scroll-y match-list" data-scroll-key="matches">${matches.length?matches.map(matchHTML).join(''):'<div class="empty"><span>🏟️</span><p>Keine Spiele.</p></div>'}</div></div>`;}
  function matchHTML(m){const a=getPlayer(m.a),b=getPlayer(m.b);return `<div class="match" data-match="${m.id}"><div class="side">${person(a)}</div><div class="score-box"><input class="score" inputmode="numeric" pattern="[0-9]*" type="number" min="0" aria-label="Tore ${esc(a?.name||'TBD')}" data-score="a" value="${m.sa??''}"><span class="dash">:</span><input class="score" inputmode="numeric" pattern="[0-9]*" type="number" min="0" aria-label="Tore ${esc(b?.name||'TBD')}" data-score="b" value="${m.sb??''}"></div><div class="side right">${person(b)}</div><div class="match-meta"><span>${m.slot!==undefined?`Slot ${m.slot+1} · `:''}${esc(m.label||'Spiel')}</span><span class="station">${esc(m.station||'')}</span></div></div>`;}
  function person(p){return p?`<div class="name">${esc(p.name)}</div>${state.kind==='fifa'&&p.team?`<div class="team">${esc(p.team)}</div>`:''}`:'<div class="name muted">wird ermittelt</div>';}
  function standings(players,matches){let out=players.map(p=>({id:p.id,name:p.name,team:p.team,sp:0,s:0,u:0,n:0,t:0,g:0,d:0,p:0}));let map=Object.fromEntries(out.map(x=>[x.id,x]));matches.filter(m=>m.a&&m.b&&m.sa!==null&&m.sa!==''&&m.sb!==null&&m.sb!=='').forEach(m=>{let a=map[m.a],b=map[m.b],x=+m.sa,y=+m.sb;if(!a||!b)return;a.sp++;b.sp++;a.t+=x;b.t+=y;a.g+=y;b.g+=x;a.d=a.t-a.g;b.d=b.t-b.g;if(x>y){a.s++;b.n++;a.p+=3}else if(y>x){b.s++;a.n++;b.p+=3}else{a.u++;b.u++;a.p++;b.p++;}});return out.sort((a,b)=>b.p-a.p||b.d-a.d||b.t-a.t||a.name.localeCompare(b.name));}
  function renderTable(players,matches,title){let data=standings(players,matches);return `<div class="section-card"><h2>${title}</h2><div class="scroll-x" data-scroll-key="table"><table class="table"><thead><tr><th>#</th><th>Spieler</th><th>Sp</th><th>S</th><th>U</th><th>N</th><th>T</th><th>Diff.</th><th>P</th></tr></thead><tbody>${data.map((x,i)=>`<tr><td class="rank">${i+1}</td><td><strong>${esc(x.name)}</strong>${state.kind==='fifa'&&x.team?` <span class="team">${esc(x.team)}</span>`:''}</td><td>${x.sp}</td><td>${x.s}</td><td>${x.u}</td><td>${x.n}</td><td>${x.t}:${x.g}</td><td>${x.d>0?'+':''}${x.d}</td><td><strong>${x.p}</strong></td></tr>`).join('')}</tbody></table></div></div>`;}
  function tableMarkup(players,matches){let data=standings(players,matches);return `<div class="scroll-x" data-scroll-key="table-${players.map(p=>p.id).join('-')}"><table class="table"><thead><tr><th>#</th><th>Spieler</th><th>Sp</th><th>S</th><th>U</th><th>N</th><th>T</th><th>Diff.</th><th>P</th></tr></thead><tbody>${data.map((x,i)=>`<tr><td class="rank">${i+1}</td><td><strong>${esc(x.name)}</strong>${state.kind==='fifa'&&x.team?` <span class="team">${esc(x.team)}</span>`:''}</td><td>${x.sp}</td><td>${x.s}</td><td>${x.u}</td><td>${x.n}</td><td>${x.t}:${x.g}</td><td>${x.d>0?'+':''}${x.d}</td><td><strong>${x.p}</strong></td></tr>`).join('')}</tbody></table></div>`;}
  function renderGroups(){return `<div class="group-wrap">${state.groupsData.map(g=>`<div class="section-card group-card"><h2>Gruppe ${g.name}</h2>${tableMarkup(g.players,g.matches)}<div class="round-title"><span>Gruppenspiele</span><span class="pill">${g.matches.filter(done).length}/${g.matches.length}</span></div><div class="scroll-y match-list" data-scroll-key="group-${g.name}">${g.matches.map(matchHTML).join('')}</div></div>`).join('')}</div>`;}
  function renderBracket(){return `<div class="section-card"><h2>K.-o.-Baum</h2>${state.bracket.length?`<div class="scroll-x" data-scroll-key="bracket"><div class="bracket">${groupByRound(state.bracket).map(([round,list])=>`<div class="bracket-round"><h3>${esc(round)}</h3>${list.map(matchHTML).join('')}</div>`).join('')}</div></div>`:'<div class="notice">Die K.-o.-Paarungen erscheinen, sobald die Gruppenphase vollständig ist.</div>'}</div>`;}
  function groupByRound(list){let x=[];list.forEach(m=>{let g=x.find(a=>a[0]===m.round);if(g)g[1].push(m);else x.push([m.round,[m]]);});return x;}
  function getPlayer(id){return state.players.find(p=>p.id===id);}
  const done=m=>m.sa!==null&&m.sa!==''&&m.sb!==null&&m.sb!=='';
  function stationNames(){if(state.kind==='normal')return Array.from({length:Math.max(1,+state.fields)},(_,i)=>`Feld ${i+1}`);let names=state.systems.flatMap(x=>Array.from({length:Math.max(1,+x.count)},(_,i)=>`${x.type} ${i+1}`));return names.length?names.map(x=>`🎮 ${x}`):['🎮 PS5 1'];}
  function stationFactory(){const names=stationNames();let n=0;return()=>names[n++%names.length];}
  function balanceStations(matches){const names=stationNames(), total=Object.fromEntries(names.map(n=>[n,0])), usage={};matches.forEach((m,i)=>{for(const p of [m.a,m.b])usage[p]??=Object.fromEntries(names.map(n=>[n,0]));let candidates=[...names].sort((x,y)=>{const px=(usage[m.a]?.[x]||0)+(usage[m.b]?.[x]||0),py=(usage[m.a]?.[y]||0)+(usage[m.b]?.[y]||0);return px-py||total[x]-total[y]||x.localeCompare(y);});m.station=candidates[0];m.slot=i;total[m.station]++;[m.a,m.b].forEach(p=>usage[p][m.station]++);});return matches;}
  function balanceGroupStations(groups){const names=stationNames(),total=Object.fromEntries(names.map(n=>[n,0])),usage={},lastGroup={},queue=[];let longest=Math.max(...groups.map(g=>g.matches.length));for(let i=0;i<longest;i++)groups.forEach(g=>{if(g.matches[i]){g.matches[i].groupName=g.name;queue.push(g.matches[i]);}});queue.forEach((m,slot)=>{for(const p of [m.a,m.b])usage[p]??=Object.fromEntries(names.map(n=>[n,0]));let allowed=names.filter(n=>names.length===1||(n!==lastGroup[m.groupName]&&n!==queue[slot-1]?.station));if(!allowed.length)allowed=names.filter(n=>n!==lastGroup[m.groupName]);if(!allowed.length)allowed=names;allowed.sort((x,y)=>{const px=(usage[m.a][x]+usage[m.b][x]),py=(usage[m.a][y]+usage[m.b][y]);return px-py||total[x]-total[y]||x.localeCompare(y);});m.station=allowed[0];m.slot=slot;lastGroup[m.groupName]=m.station;total[m.station]++;[m.a,m.b].forEach(p=>usage[p][m.station]++);});}
  function roundRobin(ids, legs=1, prefix=''){let a=[...ids];if(a.length%2)a.push(null);let n=a.length, rounds=[];for(let r=0;r<n-1;r++){let row=[];for(let i=0;i<n/2;i++){let x=a[i],y=a[n-1-i];if(x&&y)row.push([r%2?y:x,r%2?x:y]);}rounds.push(row);a.splice(1,0,a.pop());}if(legs===2)rounds=rounds.concat(rounds.map(row=>row.map(([a,b])=>[b,a])));return balanceStations(rounds.flatMap((row,r)=>row.map(([a,b],i)=>({id:uid(),a,b,sa:null,sb:null,round:prefix?`${prefix} ${r+1}`:`Spieltag ${r+1}`,label:`${prefix?prefix+' ':''}Runde ${r+1} · Spiel ${i+1}`}))));}
  function assignTeams(){if(state.kind!=='fifa')return;let pool=shuffle(currentTeams());state.players.forEach((p,i)=>{if(state.teamMode==='random')p.team=pool[i%pool.length]||'';else if(state.category==='Individuell'&&!p.team)p.team='';});}
  function makeGroups(){let count=Math.min(+state.groups||2,state.players.length), names='ABCDEFGHIJKLMNOPQRSTUVWXYZ';let buckets=Array.from({length:count},(_,i)=>({name:names[i],players:[],matches:[]}));shuffle(state.players).forEach((p,i)=>buckets[i%count].players.push(p));buckets.forEach(g=>g.matches=roundRobin(g.players.map(x=>x.id),+state.legs,`Gruppe ${g.name}`));balanceGroupStations(buckets);state.groupsData=buckets;}
  function makeKO(ids, seedGroups={}){if(!power2(ids.length)){alert('Für die K.-o.-Phase wird eine Zweierpotenz an Qualifikanten benötigt. Passe Gruppen bzw. Weiterkommende an.');return false;}let rounds=Math.log2(ids.length),bracket=[],previous=[];const names={1:'Finale',2:'Halbfinale',3:'Viertelfinale',4:'Achtelfinale'};let first=[];if(seedGroups && Object.keys(seedGroups).length===ids.length){let pools={};ids.forEach(id=>{let g=seedGroups[id];(pools[g]??=[]).push(id)});let gs=Object.keys(pools), ordered=[];while(gs.some(g=>pools[g].length))gs.forEach(g=>{if(pools[g].length)ordered.push(pools[g].shift())});for(let i=0;i<ordered.length/2;i++)first.push([ordered[i],ordered[ordered.length-1-i]]);}else{let s=shuffle(ids);for(let i=0;i<s.length;i+=2)first.push([s[i],s[i+1]]);}let station=stationFactory();for(let r=0;r<rounds;r++){let count=ids.length/2**(r+1), roundName=names[rounds-r]||`Runde ${r+1}`;let current=[];for(let i=0;i<count;i++){let m={id:uid(),a:r===0?first[i][0]:null,b:r===0?first[i][1]:null,sa:null,sb:null,round:roundName,label:roundName,station:station(),source: r?previous.slice(i*2,i*2+2).map(x=>x.id):null};current.push(m);bracket.push(m);}previous=current;}state.bracket=bracket;return true;}
  function createTournament(){assignTeams();state.matches=[];state.groupsData=[];state.bracket=[];if(state.format==='table')state.matches=roundRobin(state.players.map(p=>p.id),+state.legs);if(state.format==='ko'&&!makeKO(state.players.map(p=>p.id)))return;if(state.format==='groupsko'){let q=(+state.groups||2)*(+state.qualifiers||1);if(!power2(q)){alert('Gruppen × Weiterkommende muss für die K.-o.-Phase 2, 4, 8, 16 … ergeben.');return;}makeGroups();}if(state.format==='swiss'){state.swissRounds=Math.max(3,Math.ceil(Math.log2(state.players.length))+1);makeSwissRound(1);}state.created=true;state.activeTab=state.format==='groupsko'?'groups':state.format==='ko'?'ko':'matches';maybeStartKO();render();}
  function makeSwissRound(num){let completed=state.matches.filter(done);let ranks=standings(state.players,completed).map(x=>x.id), used=new Set(completed.map(m=>[m.a,m.b].sort().join('|'))), pairs=[], rest=[...ranks];if(num===1)rest=shuffle(rest);while(rest.length>1){let a=rest.shift(),idx=rest.findIndex(b=>!used.has([a,b].sort().join('|')));if(idx<0)idx=0;let b=rest.splice(idx,1)[0];pairs.push([a,b]);}let next=balanceStations(pairs.map(([a,b],i)=>({id:uid(),a,b,sa:null,sb:null,round:`Schweizer Runde ${num}`,label:`Runde ${num} · Tisch ${i+1}`})));next.forEach(m=>m.slot=state.matches.length+m.slot);state.matches.push(...next);}
  function winner(m){if(!done(m)||+m.sa===+m.sb)return null;return +m.sa>+m.sb?m.a:m.b;}
  function advanceBracket(){state.bracket.forEach(m=>{if(m.source){let [x,y]=m.source.map(id=>state.bracket.find(z=>z.id===id));m.a=winner(x);m.b=winner(y);}});let final=state.bracket.find(m=>m.round==='Finale');if(state.thirdPlace&&final&&final.source&&!state.bracket.some(m=>m.round==='Platz 3')){let [s1,s2]=final.source.map(id=>state.bracket.find(x=>x.id===id));if(done(s1)&&done(s2)){state.bracket.push({id:uid(),a:winner(s1)===s1.a?s1.b:s1.a,b:winner(s2)===s2.a?s2.b:s2.a,sa:null,sb:null,round:'Platz 3',label:'Spiel um Platz 3',station:stationFactory()()});}}}
  function maybeStartKO(){if(state.format!=='groupsko'||state.bracket.length||!state.groupsData.every(g=>g.matches.every(done)))return;let ids=[],groups={};state.groupsData.forEach(g=>standings(g.players,g.matches).slice(0,+state.qualifiers).forEach(x=>{ids.push(x.id);groups[x.id]=g.name;}));if(makeKO(ids,groups))state.activeTab='ko';}
  function updateScore(el){let m=findMatch(el.closest('[data-match]').dataset.match);if(!m)return;let val=el.value===''?null:Math.max(0,parseInt(el.value,10)||0);m[el.dataset.score==='a'?'sa':'sb']=val;advanceBracket();maybeStartKO();if(state.format==='swiss'){let rounds=new Set(state.matches.map(x=>x.round));let last=[...rounds].pop();let current=state.matches.filter(x=>x.round===last);let n=+last.match(/\d+/)?.[0];if(current.length&&current.every(done)&&n<state.swissRounds)makeSwissRound(n+1);}render();}
  function findMatch(id){return state.matches.find(m=>m.id===id)||state.groupsData.flatMap(g=>g.matches).find(m=>m.id===id)||state.bracket.find(m=>m.id===id);}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='continue'){$('#playersPanel')?.scrollIntoView({behavior:'smooth'});return;}if(a==='add-player'){state.players.push({id:uid(),name:`Spieler ${state.players.length+1}`,team:''});render();requestAnimationFrame(()=>document.querySelector(`[data-player-name="${state.players.at(-1).id}"]`)?.focus());}if(a==='delete-player'){state.players=state.players.filter(p=>p.id!==b.dataset.id);state.created=false;render();}if(a==='add-system'){state.systems.push({id:uid(),type:'PS5',count:1});render();}if(a==='delete-system'){state.systems=state.systems.filter(s=>s.id!==b.dataset.id);render();}if(a==='random-groups'){if(state.format==='groupsko'){makeGroups();state.created=true;state.activeTab='groups';render();}}if(a==='generate')createTournament();if(a==='tab'){state.activeTab=b.dataset.tab;render();}if(a==='reset'){state=defaults();render();window.scrollTo({top:0,behavior:'smooth'});}});
  document.addEventListener('change',e=>{if(e.target.name==='kind'){state.kind=e.target.value;if(state.kind==='fifa'&&!state.systems.length)state.systems=[{id:uid(),type:'PS5',count:1}];render();return;}if(e.target.dataset.systemType||e.target.dataset.systemCount){let s=state.systems.find(x=>x.id===(e.target.dataset.systemType||e.target.dataset.systemCount));if(s){if(e.target.dataset.systemType)s.type=e.target.value;else s.count=Math.max(1,+e.target.value||1);state.created=false;render();}return;}if(e.target.dataset.setting){let k=e.target.dataset.setting;state[k]=e.target.type==='checkbox'?e.target.checked:(['fields','legs','groups','qualifiers'].includes(k)?+e.target.value:e.target.value);state.created=false;render();return;}if(e.target.dataset.player-name){let p=getPlayer(e.target.dataset.playerName);if(p)p.name=e.target.value.trim()||'Unbenannt';render();return;}if(e.target.dataset.player-team){let p=getPlayer(e.target.dataset.playerTeam);if(p)p.team=e.target.value;save();}if(e.target.dataset.score)updateScore(e.target);});
  document.addEventListener('input',e=>{if(e.target.dataset.score){const host=e.target.closest('[data-match]');focusRestore={match:host.dataset.match,score:e.target.dataset.score};updateScore(e.target);return;}if(e.target.dataset.setting==='customTeams'){state.customTeams=e.target.value;save();}if(e.target.dataset.player-name){let p=getPlayer(e.target.dataset.playerName);if(p){p.name=e.target.value;save();}}});
  document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-player-name]')){e.preventDefault();e.target.blur();}if(e.key==='Tab'&&e.target.matches('[data-score]')){const scores=[...document.querySelectorAll('[data-score]')],i=scores.indexOf(e.target),next=scores[i+(e.shiftKey?-1:1)];if(next)focusRestore={match:next.closest('[data-match]').dataset.match,score:next.dataset.score};}});
  render();
});
